// <auto-generated />
using System;
using Home_Central.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Home_Central.Data.Migrations.Woning
{
    [DbContext(typeof(WoningDbContext))]
    partial class WoningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Home_Central.Data.Entities.WoningVerbruikModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DagTeller")
                        .HasColumnType("int");

                    b.Property<int>("GasStand")
                        .HasColumnType("int");

                    b.Property<int>("NachtTeller")
                        .HasColumnType("int");

                    b.Property<int>("Zon")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("WoningVerbruik", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
