// <auto-generated />
using System;
using Home_Central.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Home_Central.Data.Migrations.MigrationSqLite.Woning
{
    [DbContext(typeof(WoningDbContext))]
    partial class WoningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Home_Central.Data.Entities.WoningVerbruikModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DagTeller")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasStand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NachtTeller")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("datum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WoningVerbruik", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
